const mongoose = require("mongoose");

const SellerListing = new mongoose.Schema({
  dateSent: {
    type: Date,
    default: Date.now,
  },
  sentBy: String,
  query: {
    owners: Array,
    StreetAddress: String,
    Unit: String,
    PropertyType: String,
    YearBuilt: Number,
    PropertyTax: String,
    HouseSize: Object,
    LotSize: Object,
    LivingArea: Object,
    Stories: String,
    Bedrooms: Number,
    Bathrooms: Number,
    GarageSpaces: String,
    ParkingSpaces: String,
    Basement: Boolean,
    BasementFinished: String,
    BasementLivingArea: Object,
    BasementSize: Object,
    Kitchen: Object,
    "Exterior Features": Object,
    "Electricity & Lighting": Object,
    Flooring: Object,
    "Heating & Cooling": Object,
    "Doors & Windows": Object,
    "Other Features": Object,
    "Roof & Foundation": Object,
    PropertyDescription: String,
    AskingPrice: Number,
    PhotographyServices: Boolean,
    PhotographyPackage: Object,
    MarketYourHome: Object,
    LegalServices: Object,
    HouseImages: Array,
    Video: "",
    Floorplan: "",
    VirtualTour: "",
  },
  approved: String,
  location: Object,
});

module.exports = mongoose.model("SellerListing", SellerListing);
